### ISSUE TITLE
Adding ignore list to script?

### ISSUE THREAD

**Issue by basememara** [ginowu7/CleanLocalizableExample#3]
I have a few keys that are dynamically constructed. For example, if I have this:

```
enum MyEnum: String {
    case north, east, south, west
}

myLabel.text = NSLocalizedString("myenum.\(MyEnum.north)")

Localizable:
"myenum.north" = "North";
"myenum.east" = "East";
"myenum.south" = "South";
"myenum. west" = "West";
```
This rightfully gives warnings that `myenum.north`, etc found no keys, but I'd like to add these to a list of exceptions to ignore since I know what's happening in this case.

**Comment by ginowu7** [comment]
Ah, great point, we can edit the script to ignore these specific cases. Or we can edit the enum to store a `localized` value and return a `NSLocalizedString` eg:
```
enum MyEnum {
  case north, east, south, west
  var localized: String {
    switch self {
      case .north: return NSLocalizedString("myenum.north", comment: "north label")
    }
}
```

I do think that dynamically generated localizable strings are always a bit of a code smell, since there is a risk of unintentional behavior, for an example, someone accidentally deletes one of your "myenum.west" case from your localizable file. There would be no way of knowing this happened until your app is active. But with that being said, having an enum is slightly better than completely dynamic NSLocalizedString

**Comment by basememara** [comment]
I'm ok with your suggestion and adjusted my code to hardcode the localization string. I could see how if enum's are changed then the localization string could be missing or orphaned easily. Thanks for the advice!
